### ISSUE TITLE
./configure

### ISSUE THREAD

**Issue by mhardcastle** [ericmandel/funtools#10]
I can see the reasoning behind removing the configure files and cache from the git tree, but this means that the README and INSTALL instructions no longer work following a git clone.

I installed and built successfully by installing GNU autoconf and doing aclocal ; autoconf ; autoheader in the root and util, fitsy, filter, wcs directories. Maybe a small script would help?

**Comment by ericmandel** [comment]
@mhardcastle @olebole
I'm a little hesitant about whether it was a good idea to remove the configure files, but we can reconsider at some point.  For now, I added a mkconfigure script and updated the README and INSTALL to mention its use.

**Comment by olebole** [comment]
I would keep the repository as it is, but create "Release" tarballs for the public. This is [described here](https://github.com/blog/1547-release-your-software). Basically:
- [Create a tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging), like `v1.4.7`
- Go to the [releases](https://github.com/ericmandel/funtools/releases) tab in the github repository
- Press the [Draft a new release](https://github.com/ericmandel/funtools/releases/new) button
- Select the tag to use, upload the tarbal (including `configure` etc.), write some release notes and then press publish. 

This creates a complete tar file, which may be downloaded as usual.
If someone then still accesses the git repository, he shoudl know what to do (however, it would be good to describe the needed commands in the README).

**Comment by ericmandel** [comment]
This is fine ... though I have no plans to make releases. The need for autoconf is now documented in the README and there is a mkconfigure script, so we should be all set ... for now.
