### ISSUE TITLE
release tagging and conflicting man page

### ISSUE THREAD

**Issue by mudler** [ericmandel/funtools#11]
Hi,

i'm a Sabayon developer, and i wanted to fix the ebuild upstream for your project, but actually there is a problem:
https://bugs.gentoo.org/show_bug.cgi?id=536630

libbsd share with your project the same manpage named "funopen", thus there are conflicts while both packages want to be installed on the same machine.

Meanwhile i wanted also to update the ebuild, and noticed that ubuntu released the 1.4.6 version https://launchpad.net/ubuntu/+source/funtools/1.4.6+git150228-1 but i can't see that tag on the git repo, if you guys will tag it, it will be really helpful to make a "neat" package bump :)

Thanks for your time
:+1:

**Comment by ericmandel** [comment]
I added a v1.4.6 tag, as requested.

Not sure what to do about the man page name collision. I don't suppose "being there first" counts for anything!

**Comment by mudler** [comment]
@ericmandel thanks for the tag

for the man page: i actual don't know either what would be the best solution here, i noticed that both libs share the same function name and just warned that this causes issues when both packages wants to be installed. It's no race at all here who being there first :) 
what happens here is that libbsd appears to be mostly common used as it's a reverse deps for some common packages (like xdm, ettercap, bumblebee) https://packages.sabayon.org/show/libbsd,108226,sabayon-weekly,amd64,5,standard/reverse_dependencies#package-widget-show-what , thus preventing your package installed at all in gentoo in a lot of boxes

**Comment by ericmandel** [comment]
@mudler if funtools was an actively supported package, I'd be more concerned with this conflict. But active development ended in 2007 and I only keep it in github for researchers who still use it "as is". Under those circumstances, doing nothing is probably OK. One can always grab the GitHub version in cases where the conflict arises.

**Comment by mudler** [comment]
@ericmandel good enough for me :) thanks for your time
