### ISSUE TITLE
make dist tries top copy non-existent doc/Makefile

### ISSUE THREAD

**Issue by djerius** [ericmandel/funtools#14]
The `dist` target tries to perform

```
cp -p ./doc/Makefile $(DISTDIR)/doc/.; \
```
but `./doc/Makefile` doesn't exist

**Comment by ericmandel** [comment]
@djerius Fixed. The doc/Makefile got lost by an overlay zealous .gitignore rule. It's back now.

**Comment by djerius** [comment]
Thanks, that does the trick.
