### ISSUE TITLE
inconsistency in header installation directory and pkgconfig file

### ISSUE THREAD

**Issue by djerius** [ericmandel/funtools#15]
The installation directory for include files is (from Makefile.in)

```
# Directory in which to install the funtools.h include file:
INCLUDE_INSTALL_DIR =   $(INSTALL_ROOT)$(prefix)/include/funtools
```
The `@includedir@` token replaced in funtools.pc.in is:
```
% grep '"includedir"' config.status
S["includedir"]="${prefix}/include"
```
e.g., no trailing `/funtools`.  This leads to
```
% pkg-config --cflags funtools
-I/usr/local/include
```
Which implies that one should include the `funtools` directory when including the headers:

```
#include <funtools/funtools.h>
```
However, this

* Breaks old code. I think this is perfectly ok, as its preferrable 
  for funtools to stash its header files in a subdirectory and
  avoid namespace clashes.

* More importantly, doesn't work, as funtools' own header files don't
  include the ``funtools`` directory when including each other.

My suggestion would be to ensure that installed headers include the
funtools directory in their includes so as to maintain the now cleaner
namespace.

**Comment by ericmandel** [comment]
@djerius This change was suggested by @olebole and I accepted it in the spirit of allowing those who still use funtools to decide how best to maintain it. You both seem to agree on the overall architecture for includes and I'll appreciate a pull request. Otherwise I'll get to it at some point in the (probably distant) future ... maybe.

**Comment by djerius** [comment]
The simplest fix is to tweak the pkgconfig file to be consistent with the installation directory.  that keeps old code working and maintains the new file layout.  namespace collisions are still possible, of course.

I'll send a pull request for this approach

**Comment by ericmandel** [comment]
That's fine, thanks.

**Comment by olebole** [comment]
I am not sure about the solution: the `funtools/` include subdir contains very common file names like `conf.h`, `file.h` etc. Having this in the include path by default may very easily lead to errors that the wrong include file is used.
IMO the right solution would be to fix the `#include ` statements in the affected sources.

**Comment by djerius** [comment]
I agree with your analysis.  While this fix doesn't deal with the larger problem, it does allow existing code to continue to compile.

The introduction of the additional `/funtools` in the header install path broke existing code, as the pkg-config path was not consistent with the install path, and the installed header files don't use the `funtools/` path when including each other.

> IMO the right solution would be to fix the #include statements in the affected sources.

Agreed, but this must start with updating the installed `funtool` header files to use the proper relative include paths.  User code can't be fixed until the library is doing things consistently.

There's a further wrinkle which I haven't brought up before, but which I've had to deal with over years of supporting multiple platforms.  The `conf.h` file is platform dependent.  If you have a multi-arch system, or a shared installation for multiple platforms, installation of `conf.h` in the platform independent include file hierarchy will cause breakage.  I've dealt with this by installation of include files into `${exec_prefix}/include`, but I haven't done the research to know if this is the way multi-arch filesystems are supposed to be laid out.
