### ISSUE TITLE
Update zlib to latest stable version

### ISSUE THREAD

**Issue by ryandesign** [ericmandel/funtools#22]
funtools bundles zlib 1.2.3. The latest stable version is 1.2.13. If a bundled zlib is still required, please update it; otherwise, please remove it and the references to it.

**Comment by ericmandel** [comment]
My software career ended on 1 July 2022 and thus all of the software in my GitHub repository is unsupported. To my knowledge, my former employer has not undertaken to support any of this software. So my advice would be to fork a copy and make the required changes yourself ... or use something else entirely.
